#include "SslPacket.hpp"

namespace PacketParser {
namespace Packets {

SslPacket::SslPacket(const Frame* parentFrame, int packetStartIndex, int packetEndIndex)
    : AbstractPacket(parentFrame, packetStartIndex, packetEndIndex, "Secure Socket Layer")
{
}

bool SslPacket::TryParse(const Frame* parentFrame, int packetStartIndex, int packetEndIndex, AbstractPacket** result) {
    if (!result) return false;
    *result = nullptr;
    
    AbstractPacket* tlsPacket = nullptr;
    bool validTls = false /*TlsRecordPacket::TryParse*/(parentFrame, packetStartIndex, packetEndIndex, &tlsPacket);
    
    if (tlsPacket) {
        delete tlsPacket;
    }
    
    if (validTls) {
        try {
            *result = new SslPacket(parentFrame, packetStartIndex, packetEndIndex);
        } catch (...) {
            *result = nullptr;
        }
    }
    
    return validTls && *result != nullptr;
}

std::vector<AbstractPacket*> SslPacket::GetSubPackets(bool includeSelfReference) {
    std::vector<AbstractPacket*> subPackets;
    if (includeSelfReference) subPackets.push_back(this);
    
    int tlsRecordBytes = 0;
    while (PacketStartIndex() + tlsRecordBytes < PacketEndIndex()) {
        AbstractPacket* packet = nullptr;
        try {
            packet = new RawPacket(ParentFrame(), PacketStartIndex() + tlsRecordBytes, PacketEndIndex());
            if (const_cast<Frame*>(ParentFrame())->hasErrors()) {
                const_cast<Frame*>(ParentFrame())->clearErrors(); // clear the errors generated by failed parsing
                delete packet;
                packet = new RawPacket(ParentFrame(), PacketStartIndex() + tlsRecordBytes, PacketEndIndex());
            }
        } catch (...) {
            packet = new RawPacket(ParentFrame(), PacketStartIndex() + tlsRecordBytes, PacketEndIndex());
        }
        
        tlsRecordBytes += packet->PacketLength();
        subPackets.push_back(packet);
        
        for (AbstractPacket* subPacket : packet->GetSubPackets(false)) {
            subPackets.push_back(subPacket);
        }
    }
    
    return subPackets;
}

} // namespace Packets
} // namespace PacketParser
